name: test

on:
  workflow_dispatch:
jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
        - java: '17'
          os: macos-latest
          arch: arm64
          runner: macos-latest
          expander_leg: macos-latest--arm64
    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}

    - name: compile and test
      run: mvn compile test --file pom.xml
    name: build [${{ matrix.expander_leg }}]
    timeout-minutes: 150
